### PR TITLE
Fix leaking zip file when appending boxes to an executable

### PR DESCRIPTION
**Pull request by tronical**
Remove the zip file after usage.

### CODE REVIEW

**Comment by tronical** [comment]
Looks like the CI build wasn't even started. Does anyone have the rights/powers to start it?

**Comment by boyvinall** [comment]
I tried to pull your change in on #87 but I had some other wercker build issue on that.  :eyes:

**Comment by GeertJohan** [comment]
Strange about the failing build, but this seems to work fine.

**Comment by GeertJohan** [comment]
Actually, wouldn't it be better to put a `defer tmpZipFile.Close()` before that statement so we're sure our program has released the file pointer?

**Comment by tronical** [comment]
Good point. I've seen this happen on Linux, where unlinking an open file works fine. But on Windows that won't work indeed. I'll add that to be sure.

**Comment by tronical** [comment]
Apologies, I screwed up the pull request handling :(. I've opened a new PR.

**Pull request closed without merging**
