### PR TITLE
Support Windows

### PR DESCRIPTION
**Pull request by mattn**
* Handle backslash
* Be quiet if having zip command

### CODE REVIEW

**Comment by GeertJohan** [comment]
Looks good. What steps are required to make rice append work on windows? How does zip need to be installed? I'd like to include this in the readme.

**Comment by mattn** [comment]
If zip command is executable, rice should work pretty good. :+1: 
On windows, we can get zip command via http://gnuwin32.sourceforge.net/packages/zip.htm
Or cygwin/msys toolsets.

However, I'm thinking, golang have zip archiver.

http://golang.org/pkg/archive/zip/

So It will be needless if add some fixes.

**Comment by GeertJohan** [comment]
`archive/zip` doesnt support fixing the zip offset, that is why the zip cmd is still required.
More info in #7.

I'll add the instructions on zip for windows to the readme. Thanks!

**Comment by mattn** [comment]
fair enough :)

**Comment by mattn** [comment]
How about this? http://stackoverflow.com/a/7955605/720391

**Comment by Archs** [comment]
Running `rice append --exec example.exe` 

Got `Error setting zip offset: exit status 3`

I'm using zip.exe from http://gnuwin32.sourceforge.net/packages/zip.htm

It seems the zip offset is still not set correctly

**Comment by mattn** [comment]
I didn't get error. I wonder my zip.exe is from gnuwin32.

```
C:\>zip -h
Copyright (C) 1990-1999 Info-ZIP
Type 'zip "-L"' for software license.
Zip 2.3 (November 29th 1999). Usage:
zip [-options] [-b path] [-t mmddyyyy] [-n suffixes] [zipfile list] [-xi list]
  The default action is to add or replace zipfile entries from list, which
  can include the special name - to compress standard input.
  If zipfile and list are omitted, zip compresses stdin to stdout.
  -f   freshen: only changed files  -u   update: only changed or new files
  -d   delete entries in zipfile    -m   move into zipfile (delete files)
  -r   recurse into directories     -j   junk (don't record) directory names
  -0   store only                   -l   convert LF to CR LF (-ll CR LF to LF)
  -1   compress faster              -9   compress better
  -q   quiet operation              -v   verbose operation/print version info
  -c   add one-line comments        -z   add zipfile comment
  -@   read names from stdin        -o   make zipfile as old as latest entry
  -x   exclude the following names  -i   include only the following names
  -F   fix zipfile (-FF try harder) -D   do not add directory entries
  -A   adjust self-extracting exe   -J   junk zipfile prefix (unzipsfx)
  -T   test zipfile integrity       -X   eXclude eXtra file attributes
  -!   use privileges (if granted) to obtain all aspects of WinNT security
  -R   PKZIP recursion (see manual)
  -$   include volume label         -S   include system and hidden files
  -h   show this help               -n   don't compress these suffixes
```

**Comment by Archs** [comment]
Well, Is that a version problem, I'm using `Zip 3.0` on Windows XP:
```
Copyright (c) 1990-2008 Info-ZIP - Type 'zip "-L"' for software license.
Zip 3.0 (July 5th 2008). Usage:
zip [-options] [-b path] [-t mmddyyyy] [-n suffixes] [zipfile list] [-xi list]
  The default action is to add or replace zipfile entries from list, which
  can include the special name - to compress standard input.
  If zipfile and list are omitted, zip compresses stdin to stdout.
  -f   freshen: only changed files  -u   update: only changed or new files
  -d   delete entries in zipfile    -m   move into zipfile (delete OS files)
  -r   recurse into directories     -j   junk (don't record) directory names
  -0   store only                   -l   convert LF to CR LF (-ll CR LF to LF)
  -1   compress faster              -9   compress better
  -q   quiet operation              -v   verbose operation/print version info
  -c   add one-line comments        -z   add zipfile comment
  -@   read names from stdin        -o   make zipfile as old as latest entry
  -x   exclude the following names  -i   include only the following names
  -F   fix zipfile (-FF try harder) -D   do not add directory entries
  -A   adjust self-extracting exe   -J   junk zipfile prefix (unzipsfx)
  -T   test zipfile integrity       -X   eXclude eXtra file attributes
  -!   use privileges (if granted) to obtain all aspects of WinNT security
  -$   include volume label         -S   include system and hidden files
  -e   encrypt                      -n   don't compress these suffixes
  -h2  show more help
```

**Comment by Archs** [comment]
Well, I still can't make it workable.

BTW i'm using a Window XP SP3 box, is that a problem?

**Comment by mattn** [comment]
I tried on master latest. but:

    Error setting zip offset: exit status 15

**Comment by Archs** [comment]
hi @mattn , I think you idea of using the `archive/zip` is a good one. Do you think is it possible to work around the zip offset issue?

**Comment by GeertJohan** [comment]
I'm trying to get it into the go repo but it needs some more work. That will definitly fix this problem in a nice way.

**Comment by GeertJohan** [comment]
But for you @Archs it might help to install zip from http://gnuwin32.sourceforge.net/packages/zip.htm or cygwin/msys toolsets.

**Comment by Archs** [comment]
Hi @GeertJohan , I've tried the zip.exe @mattn mentioned which is `Zip 2.3 (November 29th 1999).`

Using zip 2.3 I could do `rice append --exec` successfully, but the result executable failed with the error message:

`2015/02/04 09:46:32 error opening rice.Box: could not locate box "example-files"`.  thus https://github.com/GeertJohan/go.rice/pull/38#issuecomment-72774613

**Comment by mattn** [comment]
@Archs Thanks. Maybe it is related on #44 ?

**Comment by GeertJohan** [comment]
No that's about opening a file from an already opened box. This error looks like it was returned from rice.FindBox(..)

**Comment by GeertJohan** [comment]
How is your project set up? (folders, files)

**Comment by Archs** [comment]
I was trying the `github.com/GeertJohan/go.rice/example`

**Comment by GeertJohan** [comment]
Hmm, very strange indeed... Can you try to open the binary with zip or winrar and see if that works?

**Comment by Archs** [comment]
zip,winrar or 7z can't open the appended binary file ...

I cannot do the example correctly any way. I've tried different zip exetables under XP/Win7.

Hi, @GeertJohan can the `append --exec` command be done by appending the zip archive into the go binary directly? like `cookieo9`'s [resources-go](https://github.com/cookieo9/resources-go) does:
https://github.com/cookieo9/resources-go#embedding-zip-files:
```
Create executable (eg: go build -o myApp)
Create zip file (eg: zip -r assets.zip assets)
Append zip file to executable (eg: cat assets.zip >> myApp)
Adjust the offsets in the zip header (optional) (zip -A myApp)
```

The way  [resources-go](https://github.com/cookieo9/resources-go) does appending really works under my computers, but I think `go.rice` which I've expected for a long time has a well designed API and more easily to use.

**Comment by GeertJohan** [comment]
rice does what resources-go does. It creates a zip appended to the end of the binary file, fixes the offset with `zip -A`, and thats it. So if resources-go works for you and rice doesn't, I dont understand why. Do you have the latest version of rice? (`go get -u -a github.com/GeertJohan/go.rice`).

**Pull request merged**
